export const ADD_SUBREDDIT_TOPICS = 'ADD_SUBREDDIT_TOPICS';
export const UPDATE_SELECTED_SUBREDDITS = 'UPDATE_SELECTED_SUBREDDITS';
export const ADD_SUBREDDIT_POSTS = 'ADD_SUBREDDIT_POSTS';
export const SHOW_POST_BODY = 'SHOW_POST_BODY';
